KSRC = /lib/modules/`uname -r`/build

obj-m += cinqfs.o
cinqfs-objs := cinq_meta.o cnode.o file.o fsnode.o stub.o super.o vfs.o

default:
	$(MAKE) -C $(KSRC) M=`pwd`

clean :
	$(MAKE) -C $(KSRC) M=`pwd` clean
